# Title
title: Клиент и сервер

# Description (~160 symbols)
description: >
  Объяснение того, как Forge выполняет мод.

# Contributors
contributors:
  -
    name: hohserg
    role: Автор
    github: https://github.com/hohserg