# Title
title: Small Treasures

# Description (~160 symbols)
description: >
  Создание модификации, которая добавляет сокровищницы с запертыми сундуками и ключи, которые их открывают.

# Contributors
contributors:
  -
    name: CMTV
    role: Автор
    github: https://github.com/CMTV