# Title
title: Использование Idea

# Description (~160 symbols)
description: >
  Настройка рабочего пространства для разраобтки модов с помощью IDE Idea.

# Authors
authors:
  -
    name: CMTV
    github: https://github.com/CMTV