# Title
title: Установка программ

# Description (~160 symbols)
description: >
  Установка необходимых программ, которые необходимы для разработки Minecraft модов.

# Authors
authors:
  -
    name: CMTV
    github: https://github.com/CMTV