# Title
title: Продвинутый mcmod.info

# Description (~160 symbols)
description: >
  Более подробная настройка mcmod.info файла с примерами. Пояснение некоторых неочевидных параметров.

# Contributors
contributors:
  -
    name: CMTV
    role: Автор
    github: https://github.com/CMTV