# Title
title: Сборка мода

# Description (~160 symbols)
description: >
  Все, что связано с процессом сборки мода в конечный .jar файл: описание процесса, сама сборка, полезные настройки.

# Contributors
contributors:
  -
    name: CMTV
    role: Автор
    github: https://github.com/CMTV