# Title
title: Использование Eclipse

# Description (~160 symbols)
description: >
  Настройка рабочего пространства для разраобтки модов с помощью IDE Eclipse.

# Authors
authors:
  -
    name: CMTV
    github: https://github.com/CMTV