# Title
title: Главный класс

# Description (~160 symbols)
description: >
  Основной класс в котором будет происходить регистрация команд, событий и т.д.

# Authors
authors:
  -
    name: Ivasik
    github: https://github.com/YouTy6bl4