# Title
title: Главный класс

# Description (~160 symbols)
description: >
  Основной класс в котором будет происходить регистрация команд, событий и т.д.

# Contributors
contributors:
  -
    name: Ivasik
    role: Автор
    github: https://github.com/YouTy6bl4