# Title
title: Собственный скин

# Description (~160 symbols)
description: >
  Подключение скина своего оффициального аккаунта при разработке модов.

# Authors
authors:
  -
    name: CMTV
    github: https://github.com/CMTV