# Title
title: Установка программ

# Description (~160 symbols)
description: >
  Установка необходимых программ, которые необходимы для разработки Bukkit плагинов.
# Authors
authors:
  -
    name: Ivasik
    github: https://github.com/YouTy6bl4
