# Title
title: Установка программ

# Description (~160 symbols)
description: >
  Установка необходимых программ, которые необходимы для разработки Bukkit плагинов.

# Contributors
contributors:
  -
    name: Ivasik
    role: Автор
    github: https://github.com/YouTy6bl4
